# Generated by Django 2.1.7 on 2020-10-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('buildName', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
                ('styling', models.BooleanField()),
                ('chemisenseDevice', models.BooleanField()),
                ('frontPages', models.BooleanField()),
                ('includeLeedLine', models.BooleanField()),
                ('includeResetLine', models.BooleanField()),
                ('includeMoldRisk', models.BooleanField()),
                ('includeCovidRisk', models.BooleanField()),
                ('includeCovidInfo', models.BooleanField()),
                ('includePMOne', models.BooleanField()),
                ('includeFilterLoading', models.BooleanField()),
            ],
        ),
    ]
